source 'http://rubygems.org'

gem 'rails', '3.1.3'

gem 'hpricot'
gem 'therubyracer'
gem 'haml'
gem 'paperclip'
gem 'mongoid-paperclip', :require => 'mongoid_paperclip'
gem 'jquery-rails'
gem 'redcarpet'
gem 'mongoid', '~> 2.4'
gem 'bson_ext', '~> 1.5'
gem 'mongoid-history'
gem 'devise'
gem 'cancan'
gem 'gmaps4rails'
gem 'geocoder'
gem 'rmagick'
gem 'twitter'
gem 'capistrano'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

group :development do
  gem 'nifty-generators'

end

group :test do
  # Pretty printed test output
  gem 'turn', '0.8.2', :require => false
end

group :production do

end
